language: java
jdk:
  - openjdk7

before_script:
  # Create settings.xml in 'src' directory
  - python build/settings.py

script: 

  - if [ -e "settings.xml" ]; then mvn deploy -Prelease --settings settings.xml --global-settings ~/.m2/settings.xml; else mvn package -Prelease; fi


notifications:
  email:
    recipients:
      - kenneth.gulbrandsoy@gmail.com

# Set secure environment variables. These are only valid for repository kengu/gwt-leaflet! If you run this in a cloned repo, it will fail.
env:
  global:
    # Encrypted username
    - secure: "HturNUAXXdCeIF74odVGa58P55zrjfEEfa5m/aeHsi2e3/uCC4bdGiBl1sFS\njZf9/RpCeE03ZnGDaPBeNTZpC9c/sjZ3LRU6ic6wepxhyPYtNfPIaKSl2jp5\nlZSEuoSIQx8wjYpoaSI3E7TAKXZmZnC0DOMpQD6axmshNluhjKA="
    # Encrypted password
    - secure: "DUK56l7aQX1nFi5CCNmeCXVZ1vuB/OIa9QtrRWrA6viLIFzlsVZ567jC6Efi\nZSIZcWdt/BiGn+PLO+yfQJF/Uc+0ytvien24KSxGUnE3y0zxYrdy4KRjvrt2\nm2zB4YT+UdDd+xxUTZ0NgeytnYZcbr/fEPSTscM7BBEQ+nhLB2k="
